### ISSUE TITLE
Image resolution of $photoFeed->mediaGroup->content[0]->url

### ISSUE THREAD

**Issue by davewongdev** [n0m4dz/laracasa#3]
Thanks for the work in the plugin.

Just found that the resolution of the image (got from the value of $photoFeed->mediaGroup->content[0]->url) is not good enough, about 500 px.

If we want to obtain the image with higher resolution, we can specify the imgmax attribute when getting the feed in the request path.
I have changed the line from 
$query = $query->getQueryUrl() . "?kind=comment,tag";
to
$query = $query->getQueryUrl() . "?kind=comment,tag&imgmax=1600";
in file Laracasa.php:112

Will you change it in this plugin?
More info:
https://developers.google.com/picasa-web/docs/2.0/reference#Parameters

Thanks a lot.

**Comment by n0m4dz** [comment]
Changed as you wish, thanks.
